/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.17
 *
 * Copyright (c) 2015 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtQuickWidgets.h"

#line 28 "/home/amankaushik/pyProjects/newsnotify/PyQt/sip/QtQuickWidgets/qquickwidget.sip"
#include <qquickwidget.h>
#line 29 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"

#line 28 "sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 33 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 56 "sip/QtQml/qqmlengine.sip"
#include <qqmlengine.h>
#line 36 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 96 "sip/QtCore/qurl.sip"
#include <qurl.h>
#line 39 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 42 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 249 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 45 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 449 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 48 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 438 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 51 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 204 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 54 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 341 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 57 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 232 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 60 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 403 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 63 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtQuick/qquickwindow.sip"
#include <qquickwindow.h>
#line 66 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 27 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 69 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qsurfaceformat.sip"
#include <qsurfaceformat.h>
#line 72 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qsize.sip"
#include <qsize.h>
#line 75 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 36 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 78 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtQml/qqmlerror.sip"
#include <qqmlerror.h>
#line 81 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtQuick/qquickitem.sip"
#include <qquickitem.h>
#line 84 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtQml/qqmlcontext.sip"
#include <qqmlcontext.h>
#line 87 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qicon.sip"
#include <qicon.h>
#line 90 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 93 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 32 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 96 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qwindow.sip"
#include <qwindow.h>
#line 99 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 102 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qpixmap.sip"
#include <qpixmap.h>
#line 105 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qrect.sip"
#include <qrect.h>
#line 108 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 111 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 114 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 117 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 120 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtWidgets/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 123 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtWidgets/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 126 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 192 "sip/QtCore/qglobal.sip"
#include <QtGlobal>
#line 129 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 132 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 135 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 138 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qregion.sip"
#include <qregion.h>
#line 141 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 28 "sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 144 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 147 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 150 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qfont.sip"
#include <qfont.h>
#line 153 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 156 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 487 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 159 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 542 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 162 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 591 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 165 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 564 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 168 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 580 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 171 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 643 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 174 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 283 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 177 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 460 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 180 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 416 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 183 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 390 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 186 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 376 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 189 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 362 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 192 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 52 "sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 195 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 198 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtWidgets/qaction.sip"
#include <qaction.h>
#line 201 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtWidgets/qlayout.sip"
#include <qlayout.h>
#line 204 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtWidgets/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 207 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 210 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 213 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 216 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 219 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 222 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtWidgets/qstyle.sip"
#include <qstyle.h>
#line 225 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 228 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 244 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 231 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 28 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 234 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 36 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 237 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 144 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 240 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 243 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 246 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 249 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 252 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"
#line 26 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 255 "/home/amankaushik/pyProjects/newsnotify/PyQt/QtQuickWidgets/sipQtQuickWidgetsQQuickWidget.cpp"


class sipQQuickWidget : public QQuickWidget
{
public:
    sipQQuickWidget(QWidget*);
    sipQQuickWidget(QQmlEngine*,QWidget*);
    sipQQuickWidget(const QUrl&,QWidget*);
    virtual ~sipQQuickWidget();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void disconnectNotify(const QMetaMethod&);
    void connectNotify(const QMetaMethod&);
    void customEvent(QEvent*);
    void childEvent(QChildEvent*);
    bool eventFilter(QObject*,QEvent*);
    void initPainter(QPainter*) const;
    QPainter* sharedPainter() const;
    bool nativeEvent(const QByteArray&,void*,long*);
    bool hasHeightForWidth() const;
    bool focusNextPrevChild(bool);
    QVariant inputMethodQuery(Qt::InputMethodQuery) const;
    void inputMethodEvent(QInputMethodEvent*);
    int metric(QPaintDevice::PaintDeviceMetric) const;
    void changeEvent(QEvent*);
    void dropEvent(QDropEvent*);
    void dragLeaveEvent(QDragLeaveEvent*);
    void dragMoveEvent(QDragMoveEvent*);
    void dragEnterEvent(QDragEnterEvent*);
    void actionEvent(QActionEvent*);
    void tabletEvent(QTabletEvent*);
    void contextMenuEvent(QContextMenuEvent*);
    void closeEvent(QCloseEvent*);
    void moveEvent(QMoveEvent*);
    void paintEvent(QPaintEvent*);
    void leaveEvent(QEvent*);
    void enterEvent(QEvent*);
    void focusOutEvent(QFocusEvent*);
    void focusInEvent(QFocusEvent*);
    QPaintEngine* paintEngine() const;
    int heightForWidth(int) const;
    QSize minimumSizeHint() const;
    void setVisible(bool);
    int devType() const;
    bool event(QEvent*);
    void wheelEvent(QWheelEvent*);
    void hideEvent(QHideEvent*);
    void showEvent(QShowEvent*);
    void mouseDoubleClickEvent(QMouseEvent*);
    void mouseMoveEvent(QMouseEvent*);
    void mouseReleaseEvent(QMouseEvent*);
    void mousePressEvent(QMouseEvent*);
    void keyReleaseEvent(QKeyEvent*);
    void keyPressEvent(QKeyEvent*);
    void timerEvent(QTimerEvent*);
    void resizeEvent(QResizeEvent*);
    QSize sizeHint() const;

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQQuickWidget(const sipQQuickWidget &);
    sipQQuickWidget &operator = (const sipQQuickWidget &);

    char sipPyMethods[46];
};

sipQQuickWidget::sipQQuickWidget(QWidget*a0): QQuickWidget(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQQuickWidget::sipQQuickWidget(QQmlEngine*a0,QWidget*a1): QQuickWidget(a0,a1), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQQuickWidget::sipQQuickWidget(const QUrl& a0,QWidget*a1): QQuickWidget(a0,a1), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQQuickWidget::~sipQQuickWidget()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipQQuickWidget::metaObject() const
{
    return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : sip_QtQuickWidgets_qt_metaobject(sipPySelf,sipType_QQuickWidget);
}

int sipQQuickWidget::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = QQuickWidget::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_QtQuickWidgets_qt_metacall(sipPySelf,sipType_QQuickWidget,_c,_id,_a);

    return _id;
}

void *sipQQuickWidget::qt_metacast(const char *_clname)
{
    void *sipCpp;

    return (sip_QtQuickWidgets_qt_metacast(sipPySelf, sipType_QQuickWidget, _clname, &sipCpp) ? sipCpp : QQuickWidget::qt_metacast(_clname));
}

void sipQQuickWidget::disconnectNotify(const QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
        QQuickWidget::disconnectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_46)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QMetaMethod&);

    ((sipVH_QtCore_46)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[46]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::connectNotify(const QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
        QQuickWidget::connectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_46)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QMetaMethod&);

    ((sipVH_QtCore_46)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[46]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::customEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
        QQuickWidget::customEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[25]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::childEvent(QChildEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
        QQuickWidget::childEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_47)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QChildEvent*);

    ((sipVH_QtCore_47)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[47]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

bool sipQQuickWidget::eventFilter(QObject*a0,QEvent*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return QQuickWidget::eventFilter(a0,a1);

    typedef bool (*sipVH_QtCore_26)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QObject*,QEvent*);

    return ((sipVH_QtCore_26)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[26]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0, a1);
}

void sipQQuickWidget::initPainter(QPainter*a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[5]),sipPySelf,NULL,sipName_initPainter);

    if (!sipMeth)
    {
        QQuickWidget::initPainter(a0);
        return;
    }

    typedef void (*sipVH_QtWidgets_4)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QPainter*);

    ((sipVH_QtWidgets_4)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[4]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

QPainter* sipQQuickWidget::sharedPainter() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[6]),sipPySelf,NULL,sipName_sharedPainter);

    if (!sipMeth)
        return QQuickWidget::sharedPainter();

    typedef QPainter* (*sipVH_QtWidgets_5)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtWidgets_5)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[5]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}

bool sipQQuickWidget::nativeEvent(const QByteArray& a0,void*a1,long*a2)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,NULL,sipName_nativeEvent);

    if (!sipMeth)
        return QQuickWidget::nativeEvent(a0,a1,a2);

    typedef bool (*sipVH_QtCore_58)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QByteArray&,void*,long*);

    return ((sipVH_QtCore_58)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[58]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0, a1, a2);
}

bool sipQQuickWidget::hasHeightForWidth() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[8]),sipPySelf,NULL,sipName_hasHeightForWidth);

    if (!sipMeth)
        return QQuickWidget::hasHeightForWidth();

    typedef bool (*sipVH_QtCore_7)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtCore_7)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[7]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}

bool sipQQuickWidget::focusNextPrevChild(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[9],sipPySelf,NULL,sipName_focusNextPrevChild);

    if (!sipMeth)
        return QQuickWidget::focusNextPrevChild(a0);

    typedef bool (*sipVH_QtWidgets_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool);

    return ((sipVH_QtWidgets_6)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[6]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

QVariant sipQQuickWidget::inputMethodQuery(Qt::InputMethodQuery a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[10]),sipPySelf,NULL,sipName_inputMethodQuery);

    if (!sipMeth)
        return QQuickWidget::inputMethodQuery(a0);

    typedef QVariant (*sipVH_QtWidgets_7)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, Qt::InputMethodQuery);

    return ((sipVH_QtWidgets_7)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[7]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::inputMethodEvent(QInputMethodEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[11],sipPySelf,NULL,sipName_inputMethodEvent);

    if (!sipMeth)
    {
        QQuickWidget::inputMethodEvent(a0);
        return;
    }

    typedef void (*sipVH_QtWidgets_8)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QInputMethodEvent*);

    ((sipVH_QtWidgets_8)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[8]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

int sipQQuickWidget::metric(QPaintDevice::PaintDeviceMetric a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[12]),sipPySelf,NULL,sipName_metric);

    if (!sipMeth)
        return QQuickWidget::metric(a0);

    typedef int (*sipVH_QtGui_28)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QPaintDevice::PaintDeviceMetric);

    return ((sipVH_QtGui_28)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[28]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::changeEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[13],sipPySelf,NULL,sipName_changeEvent);

    if (!sipMeth)
    {
        QQuickWidget::changeEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[25]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::dropEvent(QDropEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[14],sipPySelf,NULL,sipName_dropEvent);

    if (!sipMeth)
    {
        QQuickWidget::dropEvent(a0);
        return;
    }

    typedef void (*sipVH_QtWidgets_9)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QDropEvent*);

    ((sipVH_QtWidgets_9)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[9]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::dragLeaveEvent(QDragLeaveEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[15],sipPySelf,NULL,sipName_dragLeaveEvent);

    if (!sipMeth)
    {
        QQuickWidget::dragLeaveEvent(a0);
        return;
    }

    typedef void (*sipVH_QtWidgets_10)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QDragLeaveEvent*);

    ((sipVH_QtWidgets_10)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[10]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::dragMoveEvent(QDragMoveEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[16],sipPySelf,NULL,sipName_dragMoveEvent);

    if (!sipMeth)
    {
        QQuickWidget::dragMoveEvent(a0);
        return;
    }

    typedef void (*sipVH_QtWidgets_11)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QDragMoveEvent*);

    ((sipVH_QtWidgets_11)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[11]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::dragEnterEvent(QDragEnterEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[17],sipPySelf,NULL,sipName_dragEnterEvent);

    if (!sipMeth)
    {
        QQuickWidget::dragEnterEvent(a0);
        return;
    }

    typedef void (*sipVH_QtWidgets_12)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QDragEnterEvent*);

    ((sipVH_QtWidgets_12)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[12]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::actionEvent(QActionEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[18],sipPySelf,NULL,sipName_actionEvent);

    if (!sipMeth)
    {
        QQuickWidget::actionEvent(a0);
        return;
    }

    typedef void (*sipVH_QtWidgets_13)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QActionEvent*);

    ((sipVH_QtWidgets_13)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[13]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::tabletEvent(QTabletEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[19],sipPySelf,NULL,sipName_tabletEvent);

    if (!sipMeth)
    {
        QQuickWidget::tabletEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_0)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QTabletEvent*);

    ((sipVH_QtGui_0)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[0]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::contextMenuEvent(QContextMenuEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[20],sipPySelf,NULL,sipName_contextMenuEvent);

    if (!sipMeth)
    {
        QQuickWidget::contextMenuEvent(a0);
        return;
    }

    typedef void (*sipVH_QtWidgets_14)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QContextMenuEvent*);

    ((sipVH_QtWidgets_14)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[14]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::closeEvent(QCloseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[21],sipPySelf,NULL,sipName_closeEvent);

    if (!sipMeth)
    {
        QQuickWidget::closeEvent(a0);
        return;
    }

    typedef void (*sipVH_QtWidgets_15)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QCloseEvent*);

    ((sipVH_QtWidgets_15)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[15]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::moveEvent(QMoveEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[22],sipPySelf,NULL,sipName_moveEvent);

    if (!sipMeth)
    {
        QQuickWidget::moveEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_8)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QMoveEvent*);

    ((sipVH_QtGui_8)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[8]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::paintEvent(QPaintEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[23],sipPySelf,NULL,sipName_paintEvent);

    if (!sipMeth)
    {
        QQuickWidget::paintEvent(a0);
        return;
    }

    typedef void (*sipVH_QtWidgets_0)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QPaintEvent*);

    ((sipVH_QtWidgets_0)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[0]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::leaveEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[24],sipPySelf,NULL,sipName_leaveEvent);

    if (!sipMeth)
    {
        QQuickWidget::leaveEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[25]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::enterEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[25],sipPySelf,NULL,sipName_enterEvent);

    if (!sipMeth)
    {
        QQuickWidget::enterEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[25]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::focusOutEvent(QFocusEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[26],sipPySelf,NULL,sipName_focusOutEvent);

    if (!sipMeth)
    {
        QQuickWidget::focusOutEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_7)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QFocusEvent*);

    ((sipVH_QtGui_7)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[7]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::focusInEvent(QFocusEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[27],sipPySelf,NULL,sipName_focusInEvent);

    if (!sipMeth)
    {
        QQuickWidget::focusInEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_7)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QFocusEvent*);

    ((sipVH_QtGui_7)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[7]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

QPaintEngine* sipQQuickWidget::paintEngine() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[28]),sipPySelf,NULL,sipName_paintEngine);

    if (!sipMeth)
        return QQuickWidget::paintEngine();

    typedef QPaintEngine* (*sipVH_QtGui_29)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtGui_29)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[29]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}

int sipQQuickWidget::heightForWidth(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[29]),sipPySelf,NULL,sipName_heightForWidth);

    if (!sipMeth)
        return QQuickWidget::heightForWidth(a0);

    typedef int (*sipVH_QtCore_61)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return ((sipVH_QtCore_61)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[61]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

QSize sipQQuickWidget::minimumSizeHint() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[30]),sipPySelf,NULL,sipName_minimumSizeHint);

    if (!sipMeth)
        return QQuickWidget::minimumSizeHint();

    typedef QSize (*sipVH_QtGui_12)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtGui_12)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[12]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}

void sipQQuickWidget::setVisible(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[31],sipPySelf,NULL,sipName_setVisible);

    if (!sipMeth)
    {
        QQuickWidget::setVisible(a0);
        return;
    }

    typedef void (*sipVH_QtWidgets_1)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool);

    ((sipVH_QtWidgets_1)(sipModuleAPI_QtQuickWidgets_QtWidgets->em_virthandlers[1]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

int sipQQuickWidget::devType() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[32]),sipPySelf,NULL,sipName_devType);

    if (!sipMeth)
        return QQuickWidget::devType();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[6]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}

bool sipQQuickWidget::event(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[33],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return QQuickWidget::event(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    return ((sipVH_QtCore_5)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[5]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::wheelEvent(QWheelEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[34],sipPySelf,NULL,sipName_wheelEvent);

    if (!sipMeth)
    {
        QQuickWidget::wheelEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_2)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QWheelEvent*);

    ((sipVH_QtGui_2)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[2]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::hideEvent(QHideEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[35],sipPySelf,NULL,sipName_hideEvent);

    if (!sipMeth)
    {
        QQuickWidget::hideEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_5)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QHideEvent*);

    ((sipVH_QtGui_5)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[5]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::showEvent(QShowEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[36],sipPySelf,NULL,sipName_showEvent);

    if (!sipMeth)
    {
        QQuickWidget::showEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QShowEvent*);

    ((sipVH_QtGui_6)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[6]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::mouseDoubleClickEvent(QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[37],sipPySelf,NULL,sipName_mouseDoubleClickEvent);

    if (!sipMeth)
    {
        QQuickWidget::mouseDoubleClickEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_3)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QMouseEvent*);

    ((sipVH_QtGui_3)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[3]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::mouseMoveEvent(QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[38],sipPySelf,NULL,sipName_mouseMoveEvent);

    if (!sipMeth)
    {
        QQuickWidget::mouseMoveEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_3)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QMouseEvent*);

    ((sipVH_QtGui_3)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[3]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::mouseReleaseEvent(QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[39],sipPySelf,NULL,sipName_mouseReleaseEvent);

    if (!sipMeth)
    {
        QQuickWidget::mouseReleaseEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_3)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QMouseEvent*);

    ((sipVH_QtGui_3)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[3]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::mousePressEvent(QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[40],sipPySelf,NULL,sipName_mousePressEvent);

    if (!sipMeth)
    {
        QQuickWidget::mousePressEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_3)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QMouseEvent*);

    ((sipVH_QtGui_3)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[3]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::keyReleaseEvent(QKeyEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[41],sipPySelf,NULL,sipName_keyReleaseEvent);

    if (!sipMeth)
    {
        QQuickWidget::keyReleaseEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_4)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QKeyEvent*);

    ((sipVH_QtGui_4)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[4]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::keyPressEvent(QKeyEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[42],sipPySelf,NULL,sipName_keyPressEvent);

    if (!sipMeth)
    {
        QQuickWidget::keyPressEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_4)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QKeyEvent*);

    ((sipVH_QtGui_4)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[4]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::timerEvent(QTimerEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[43],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
        QQuickWidget::timerEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_9)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QTimerEvent*);

    ((sipVH_QtCore_9)(sipModuleAPI_QtQuickWidgets_QtCore->em_virthandlers[9]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

void sipQQuickWidget::resizeEvent(QResizeEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[44],sipPySelf,NULL,sipName_resizeEvent);

    if (!sipMeth)
    {
        QQuickWidget::resizeEvent(a0);
        return;
    }

    typedef void (*sipVH_QtGui_9)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QResizeEvent*);

    ((sipVH_QtGui_9)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[9]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth, a0);
}

QSize sipQQuickWidget::sizeHint() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[45]),sipPySelf,NULL,sipName_sizeHint);

    if (!sipMeth)
        return QQuickWidget::sizeHint();

    typedef QSize (*sipVH_QtGui_12)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtGui_12)(sipModuleAPI_QtQuickWidgets_QtGui->em_virthandlers[12]))(sipGILState, sipModuleAPI_QtQuickWidgets_QtCore->em_virterrorhandlers[0], sipPySelf, sipMeth);
}


PyDoc_STRVAR(doc_QQuickWidget_source, "QQuickWidget.source() -> QUrl");

extern "C" {static PyObject *meth_QQuickWidget_source(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_source(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QQuickWidget, &sipCpp))
        {
            QUrl*sipRes;

            sipRes = new QUrl(sipCpp->source());

            return sipConvertFromNewType(sipRes,sipType_QUrl,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_source, doc_QQuickWidget_source);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_engine, "QQuickWidget.engine() -> QQmlEngine");

extern "C" {static PyObject *meth_QQuickWidget_engine(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_engine(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QQuickWidget, &sipCpp))
        {
            QQmlEngine*sipRes;

            sipRes = sipCpp->engine();

            return sipConvertFromType(sipRes,sipType_QQmlEngine,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_engine, doc_QQuickWidget_engine);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_rootContext, "QQuickWidget.rootContext() -> QQmlContext");

extern "C" {static PyObject *meth_QQuickWidget_rootContext(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_rootContext(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QQuickWidget, &sipCpp))
        {
            QQmlContext*sipRes;

            sipRes = sipCpp->rootContext();

            return sipConvertFromType(sipRes,sipType_QQmlContext,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_rootContext, doc_QQuickWidget_rootContext);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_rootObject, "QQuickWidget.rootObject() -> QQuickItem");

extern "C" {static PyObject *meth_QQuickWidget_rootObject(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_rootObject(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QQuickWidget, &sipCpp))
        {
            QQuickItem*sipRes;

            sipRes = sipCpp->rootObject();

            return sipConvertFromType(sipRes,sipType_QQuickItem,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_rootObject, doc_QQuickWidget_rootObject);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_resizeMode, "QQuickWidget.resizeMode() -> QQuickWidget.ResizeMode");

extern "C" {static PyObject *meth_QQuickWidget_resizeMode(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_resizeMode(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QQuickWidget, &sipCpp))
        {
            QQuickWidget::ResizeMode sipRes;

            sipRes = sipCpp->resizeMode();

            return sipConvertFromEnum(sipRes,sipType_QQuickWidget_ResizeMode);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_resizeMode, doc_QQuickWidget_resizeMode);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_setResizeMode, "QQuickWidget.setResizeMode(QQuickWidget.ResizeMode)");

extern "C" {static PyObject *meth_QQuickWidget_setResizeMode(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_setResizeMode(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QQuickWidget::ResizeMode a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QQuickWidget_ResizeMode, &a0))
        {
            sipCpp->setResizeMode(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_setResizeMode, doc_QQuickWidget_setResizeMode);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_status, "QQuickWidget.status() -> QQuickWidget.Status");

extern "C" {static PyObject *meth_QQuickWidget_status(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_status(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QQuickWidget, &sipCpp))
        {
            QQuickWidget::Status sipRes;

            sipRes = sipCpp->status();

            return sipConvertFromEnum(sipRes,sipType_QQuickWidget_Status);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_status, doc_QQuickWidget_status);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_errors, "QQuickWidget.errors() -> list-of-QQmlError");

extern "C" {static PyObject *meth_QQuickWidget_errors(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_errors(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QQuickWidget, &sipCpp))
        {
            QList<QQmlError>*sipRes;

            sipRes = new QList<QQmlError>(sipCpp->errors());

            return sipConvertFromNewType(sipRes,sipType_QList_0100QQmlError,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_errors, doc_QQuickWidget_errors);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_sizeHint, "QQuickWidget.sizeHint() -> QSize");

extern "C" {static PyObject *meth_QQuickWidget_sizeHint(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_sizeHint(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QQuickWidget, &sipCpp))
        {
            QSize*sipRes;

            sipRes = new QSize((sipSelfWasArg ? sipCpp->QQuickWidget::sizeHint() : sipCpp->sizeHint()));

            return sipConvertFromNewType(sipRes,sipType_QSize,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_sizeHint, doc_QQuickWidget_sizeHint);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_initialSize, "QQuickWidget.initialSize() -> QSize");

extern "C" {static PyObject *meth_QQuickWidget_initialSize(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_initialSize(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QQuickWidget, &sipCpp))
        {
            QSize*sipRes;

            sipRes = new QSize(sipCpp->initialSize());

            return sipConvertFromNewType(sipRes,sipType_QSize,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_initialSize, doc_QQuickWidget_initialSize);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_setFormat, "QQuickWidget.setFormat(QSurfaceFormat)");

extern "C" {static PyObject *meth_QQuickWidget_setFormat(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_setFormat(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QSurfaceFormat* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QSurfaceFormat, &a0))
        {
            sipCpp->setFormat(*a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_setFormat, doc_QQuickWidget_setFormat);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_format, "QQuickWidget.format() -> QSurfaceFormat");

extern "C" {static PyObject *meth_QQuickWidget_format(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_format(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QQuickWidget, &sipCpp))
        {
            QSurfaceFormat*sipRes;

            sipRes = new QSurfaceFormat(sipCpp->format());

            return sipConvertFromNewType(sipRes,sipType_QSurfaceFormat,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_format, doc_QQuickWidget_format);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_setSource, "QQuickWidget.setSource(QUrl)");

extern "C" {static PyObject *meth_QQuickWidget_setSource(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_setSource(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QUrl* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QUrl, &a0))
        {
            sipCpp->setSource(*a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_setSource, doc_QQuickWidget_setSource);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_resizeEvent, "QQuickWidget.resizeEvent(QResizeEvent)");

extern "C" {static PyObject *meth_QQuickWidget_resizeEvent(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_resizeEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QResizeEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QResizeEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QQuickWidget::resizeEvent(a0) : sipCpp->resizeEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_resizeEvent, doc_QQuickWidget_resizeEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_timerEvent, "QQuickWidget.timerEvent(QTimerEvent)");

extern "C" {static PyObject *meth_QQuickWidget_timerEvent(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_timerEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QTimerEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QTimerEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QQuickWidget::timerEvent(a0) : sipCpp->timerEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_timerEvent, doc_QQuickWidget_timerEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_keyPressEvent, "QQuickWidget.keyPressEvent(QKeyEvent)");

extern "C" {static PyObject *meth_QQuickWidget_keyPressEvent(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_keyPressEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QKeyEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QKeyEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QQuickWidget::keyPressEvent(a0) : sipCpp->keyPressEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_keyPressEvent, doc_QQuickWidget_keyPressEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_keyReleaseEvent, "QQuickWidget.keyReleaseEvent(QKeyEvent)");

extern "C" {static PyObject *meth_QQuickWidget_keyReleaseEvent(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_keyReleaseEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QKeyEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QKeyEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QQuickWidget::keyReleaseEvent(a0) : sipCpp->keyReleaseEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_keyReleaseEvent, doc_QQuickWidget_keyReleaseEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_mousePressEvent, "QQuickWidget.mousePressEvent(QMouseEvent)");

extern "C" {static PyObject *meth_QQuickWidget_mousePressEvent(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_mousePressEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QMouseEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QMouseEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QQuickWidget::mousePressEvent(a0) : sipCpp->mousePressEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_mousePressEvent, doc_QQuickWidget_mousePressEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_mouseReleaseEvent, "QQuickWidget.mouseReleaseEvent(QMouseEvent)");

extern "C" {static PyObject *meth_QQuickWidget_mouseReleaseEvent(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_mouseReleaseEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QMouseEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QMouseEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QQuickWidget::mouseReleaseEvent(a0) : sipCpp->mouseReleaseEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_mouseReleaseEvent, doc_QQuickWidget_mouseReleaseEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_mouseMoveEvent, "QQuickWidget.mouseMoveEvent(QMouseEvent)");

extern "C" {static PyObject *meth_QQuickWidget_mouseMoveEvent(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_mouseMoveEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QMouseEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QMouseEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QQuickWidget::mouseMoveEvent(a0) : sipCpp->mouseMoveEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_mouseMoveEvent, doc_QQuickWidget_mouseMoveEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_mouseDoubleClickEvent, "QQuickWidget.mouseDoubleClickEvent(QMouseEvent)");

extern "C" {static PyObject *meth_QQuickWidget_mouseDoubleClickEvent(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_mouseDoubleClickEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QMouseEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QMouseEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QQuickWidget::mouseDoubleClickEvent(a0) : sipCpp->mouseDoubleClickEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_mouseDoubleClickEvent, doc_QQuickWidget_mouseDoubleClickEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_showEvent, "QQuickWidget.showEvent(QShowEvent)");

extern "C" {static PyObject *meth_QQuickWidget_showEvent(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_showEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QShowEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QShowEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QQuickWidget::showEvent(a0) : sipCpp->showEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_showEvent, doc_QQuickWidget_showEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_hideEvent, "QQuickWidget.hideEvent(QHideEvent)");

extern "C" {static PyObject *meth_QQuickWidget_hideEvent(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_hideEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QHideEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QHideEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QQuickWidget::hideEvent(a0) : sipCpp->hideEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_hideEvent, doc_QQuickWidget_hideEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_wheelEvent, "QQuickWidget.wheelEvent(QWheelEvent)");

extern "C" {static PyObject *meth_QQuickWidget_wheelEvent(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_wheelEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QWheelEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QWheelEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp->QQuickWidget::wheelEvent(a0) : sipCpp->wheelEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_wheelEvent, doc_QQuickWidget_wheelEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QQuickWidget_event, "QQuickWidget.event(QEvent) -> bool");

extern "C" {static PyObject *meth_QQuickWidget_event(PyObject *, PyObject *);}
static PyObject *meth_QQuickWidget_event(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QEvent* a0;
        QQuickWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QQuickWidget, &sipCpp, sipType_QEvent, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QQuickWidget::event(a0) : sipCpp->event(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QQuickWidget, sipName_event, doc_QQuickWidget_event);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QQuickWidget(void *, const sipTypeDef *);}
static void *cast_QQuickWidget(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QQuickWidget)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QWidget)->ctd_cast((QWidget *)(QQuickWidget *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QQuickWidget(void *, int);}
static void release_QQuickWidget(void *sipCppV,int)
{
    QQuickWidget *sipCpp = reinterpret_cast<QQuickWidget *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QQuickWidget(sipSimpleWrapper *);}
static void dealloc_QQuickWidget(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQQuickWidget *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QQuickWidget(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_type_QQuickWidget(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QQuickWidget(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQQuickWidget *sipCpp = 0;

    {
        QWidget* a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JH", sipType_QWidget, &a0, sipOwner))
        {
            sipCpp = new sipQQuickWidget(a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        QQmlEngine* a0;
        QWidget* a1;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J8JH", sipType_QQmlEngine, &a0, sipType_QWidget, &a1, sipOwner))
        {
            sipCpp = new sipQQuickWidget(a0,a1);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const QUrl* a0;
        QWidget* a1 = 0;

        static const char *sipKwdList[] = {
            NULL,
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "J9|JH", sipType_QUrl, &a0, sipType_QWidget, &a1, sipOwner))
        {
            sipCpp = new sipQQuickWidget(*a0,a1);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QQuickWidget[] = {{454, 2, 1}};


static PyMethodDef methods_QQuickWidget[] = {
    {SIP_MLNAME_CAST(sipName_engine), meth_QQuickWidget_engine, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_engine)},
    {SIP_MLNAME_CAST(sipName_errors), meth_QQuickWidget_errors, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_errors)},
    {SIP_MLNAME_CAST(sipName_event), meth_QQuickWidget_event, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_event)},
    {SIP_MLNAME_CAST(sipName_format), meth_QQuickWidget_format, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_format)},
    {SIP_MLNAME_CAST(sipName_hideEvent), meth_QQuickWidget_hideEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_hideEvent)},
    {SIP_MLNAME_CAST(sipName_initialSize), meth_QQuickWidget_initialSize, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_initialSize)},
    {SIP_MLNAME_CAST(sipName_keyPressEvent), meth_QQuickWidget_keyPressEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_keyPressEvent)},
    {SIP_MLNAME_CAST(sipName_keyReleaseEvent), meth_QQuickWidget_keyReleaseEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_keyReleaseEvent)},
    {SIP_MLNAME_CAST(sipName_mouseDoubleClickEvent), meth_QQuickWidget_mouseDoubleClickEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_mouseDoubleClickEvent)},
    {SIP_MLNAME_CAST(sipName_mouseMoveEvent), meth_QQuickWidget_mouseMoveEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_mouseMoveEvent)},
    {SIP_MLNAME_CAST(sipName_mousePressEvent), meth_QQuickWidget_mousePressEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_mousePressEvent)},
    {SIP_MLNAME_CAST(sipName_mouseReleaseEvent), meth_QQuickWidget_mouseReleaseEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_mouseReleaseEvent)},
    {SIP_MLNAME_CAST(sipName_resizeEvent), meth_QQuickWidget_resizeEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_resizeEvent)},
    {SIP_MLNAME_CAST(sipName_resizeMode), meth_QQuickWidget_resizeMode, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_resizeMode)},
    {SIP_MLNAME_CAST(sipName_rootContext), meth_QQuickWidget_rootContext, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_rootContext)},
    {SIP_MLNAME_CAST(sipName_rootObject), meth_QQuickWidget_rootObject, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_rootObject)},
    {SIP_MLNAME_CAST(sipName_setFormat), meth_QQuickWidget_setFormat, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_setFormat)},
    {SIP_MLNAME_CAST(sipName_setResizeMode), meth_QQuickWidget_setResizeMode, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_setResizeMode)},
    {SIP_MLNAME_CAST(sipName_setSource), meth_QQuickWidget_setSource, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_setSource)},
    {SIP_MLNAME_CAST(sipName_showEvent), meth_QQuickWidget_showEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_showEvent)},
    {SIP_MLNAME_CAST(sipName_sizeHint), meth_QQuickWidget_sizeHint, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_sizeHint)},
    {SIP_MLNAME_CAST(sipName_source), meth_QQuickWidget_source, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_source)},
    {SIP_MLNAME_CAST(sipName_status), meth_QQuickWidget_status, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_status)},
    {SIP_MLNAME_CAST(sipName_timerEvent), meth_QQuickWidget_timerEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_timerEvent)},
    {SIP_MLNAME_CAST(sipName_wheelEvent), meth_QQuickWidget_wheelEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QQuickWidget_wheelEvent)}
};

static sipEnumMemberDef enummembers_QQuickWidget[] = {
    {sipName_Error, static_cast<int>(QQuickWidget::Error), 2},
    {sipName_Loading, static_cast<int>(QQuickWidget::Loading), 2},
    {sipName_Null, static_cast<int>(QQuickWidget::Null), 2},
    {sipName_Ready, static_cast<int>(QQuickWidget::Ready), 2},
    {sipName_SizeRootObjectToView, static_cast<int>(QQuickWidget::SizeRootObjectToView), 1},
    {sipName_SizeViewToRootObject, static_cast<int>(QQuickWidget::SizeViewToRootObject), 1},
};


/* Define this type's signals. */
static const pyqt5QtSignal signals_QQuickWidget[] = {
    {"sceneGraphError(QQuickWindow::SceneGraphError,QString)", "\1QQuickWidget.sceneGraphError[QQuickWindow.SceneGraphError, str]", 0, 0},
    {"statusChanged(QQuickWidget::Status)", "\1QQuickWidget.statusChanged[QQuickWidget.Status]", 0, 0},
    {0, 0, 0, 0}
};

PyDoc_STRVAR(doc_QQuickWidget, "\1QQuickWidget(QWidget parent=None)\n"
    "QQuickWidget(QQmlEngine, QWidget)\n"
    "QQuickWidget(QUrl, QWidget parent=None)");


pyqt5ClassTypeDef sipTypeDef_QtQuickWidgets_QQuickWidget = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QQuickWidget,
        {0}
    },
    {
        sipNameNr_QQuickWidget,
        {0, 0, 1},
        25, methods_QQuickWidget,
        6, enummembers_QQuickWidget,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QQuickWidget,
    -1,
    -1,
    supers_QQuickWidget,
    0,
    init_type_QQuickWidget,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QQuickWidget,
    0,
    0,
    0,
    release_QQuickWidget,
    cast_QQuickWidget,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QQuickWidget::staticMetaObject,
    0,
    signals_QQuickWidget,
    0
};
